import './app-header.js';
import './test-header.js';
import './test/CalendarLayoutComponentTests';
import './test/CalendarLayoutComponentTests(day)';
import './test/CalendarLayoutComponentTests(month)';
import './test/CalendarLayoutComponentTests(week)';
import './test/CalendarLayoutComponentTests(with-decorators)';
import './test/ContentClassTests';
import './test/ContentComponentTests';
import './test/ContentLayerFactoryTests';
import './test/DateCursors.dateCursorFactoryTests';
import './test/DateCursors.DayViewCursorRangeTests';
import './test/DateCursors.MonthViewCursorRangeTests';
import './test/DateCursors.WeekViewCursorRangeTests';
import './test/DateCursorStateTests';
import './test/HeaderComponentTests';
import './test/ModalComponentTests';
import './test/settingsFactoryTests';

QUnit.start();
