import './app-header.js';
import './test-header.js';
import './test/CalendarLayoutComponentTests.js';
import './test/CalendarLayoutComponentTests(day).js';
import './test/CalendarLayoutComponentTests(month).js';
import './test/CalendarLayoutComponentTests(week).js';
import './test/CalendarLayoutComponentTests(with-decorators).js';
import './test/ContentClassTests.js';
import './test/ContentComponentTests.js';
import './test/ContentLayerFactoryTests.js';
import './test/DateCursors.DateCursorFactoryTests.js';
import './test/DateCursors.DayViewCursorRangeTests.js';
import './test/DateCursors.MonthViewCursorRangeTests.js';
import './test/DateCursors.WeekViewCursorRangeTests.js';
import './test/DateCursorStateTests.js';
import './test/ModalComponentTests.js';
import './test/settingsFactoryTests.js';
import './test/ToolbarComponentTests.js';
import './test/ToolbarTests.js';

QUnit.start();
