import './main.js';
import './test-header.js';
import './test/event/CalendarLayoutComponentTests(with-event-extension).js';
import './test/event/EventExtensionTests.js';
import './test/event/EventModalComponentTests.js';
import './test/event/EventTests.js';
import './test/event/MonthViewEventRenderingTests.js';
import './test/event/RepositoryFactoriesTests.js';
import './test/event/WeekAndDayViewEventRenderingTests.js';
import './test/CalendarLayoutComponentTests.js';
import './test/CalendarLayoutComponentTests(day).js';
import './test/CalendarLayoutComponentTests(month).js';
import './test/CalendarLayoutComponentTests(week).js';
import './test/CalendarLayoutComponentTests(with-extension).js';
import './test/ContentClassTests.js';
import './test/ContentComponentTests.js';
import './test/ExtensionFactoryTests.js';
import './test/DateCursors.DateCursorFactoryTests.js';
import './test/DateCursors.DayViewCursorRangeTests.js';
import './test/DateCursors.MonthViewCursorRangeTests.js';
import './test/DateCursors.WeekViewCursorRangeTests.js';
import './test/DateCursorStateTests.js';
import './test/ModalComponentTests.js';
import './test/settingsFactoryTests.js';
import './test/ToolbarComponentTests.js';

QUnit.start();
